### ISSUE TITLE
IE 11 - Profile Dashboard

### ISSUE THREAD

**Issue by burgwyn** [USStateDept/State-TalentMAP#1472]
* Padding on left menu
* Bid List scroll
* Bottom padding on
  * Notifications
  * Bid List

![image](https://user-images.githubusercontent.com/661204/36597226-739d562a-1876-11e8-8197-0d619a5c410b.png)

**Comment by mjoyce91** [comment]
Were you using the standard zoom settings (100%) or were you zoomed out?

**Comment by mjoyce91** [comment]
Looks like the extra white space was due to the CSS rule `unset` being used, which is not supported in IE11. I'm going to make a PR to fix this issue, and then a separate issue to address migrating from `unset` to a cross-compatible rule.
