### ISSUE TITLE
Upcoming features comms

### ISSUE THREAD

**Issue by wongperson** [USStateDept/State-TalentMAP#1503]
**Story**
As a TalentMAP user,
I want to be able to preview new features coming to TalentMAP
so that I can familiarize myself with TalentMAP and provide feedback to the product team

**Background**
In order to prevent users from interpreting features as active, create static-image and text content pages explaining bid tracker and transactional features for RC1, replacing the existing active feature pages in user profiles.

**Acceptance criteria**
- People visiting the site understand that new features are coming in an modular fashion

**Scope**
- Bid tracker page
- About page - possibly a how to use page?  (requires exploration)
- Profile page for CDO/AO users - explore using standard channels of communication

**Comment by wongperson** [comment]
@burgwyn @cydneycappello @esgoodman @krisdelacruz Need to split this up into epics per scope coverage and determine tools and outlets to broadcast features upcoming.

**Comment by esgoodman** [comment]
Related to #1435.

**Comment by RyanSibley** [comment]
you're right that this is more of an epic, and the first thing I wonder is if we need everything that's in scope right now...

I'm also wondering why we'd have deactivated features? My gut tells me that would frustrate users, even if we're clear that they are _to come_.

**Comment by RyanSibley** [comment]
After talking with @wongperson , I came away with a few things we might want to consider:

- Separate messaging to people like CDOs who need to know what relevant feature are in the pipeline for them. Included in that could be an overview of what the current site is being used for (searching and saving to favorites). Maybe this is a memo or email sent out to people like this?
- Content on the site that tells potential bidders how they can currently use this site (research, search and favs)
- Telling bidders that favorites is different than their bidlist
- Telling bidders that they still need to use FSbid to apply (can we provide a direct link)?
- Research the needs of people using the backend to make sure we have the right features planned
