### ISSUE TITLE
Bid tracker page

### ISSUE THREAD

**Issue by wongperson** [USStateDept/State-TalentMAP#1572]
**Story**
As a TalentMAP bidder,
I want to preview how my bidding will work on TalentMAP
so I can familiarize myself with the future of TalentMAP

**Acceptance Criteria**
- People visiting the site understand that new bidding and tracker features are coming in a modular fashion
- Replace dedicated page with static image and walkthrough text to preview upcoming features without making deactivated content/features available.

**Comment by sddecker** [comment]
No one wants it :)
