### ISSUE TITLE
About / How-to page

### ISSUE THREAD

**Issue by wongperson** [USStateDept/State-TalentMAP#1573]
**Story**
As a TalentMAP bidder,
I want to know what TalentMAP can currently do
so I can effectively research posts and positions for my bidding cycle

**Acceptance Criteria**
- Content in TalentMAP that potential bidders how they can currently use this site 
  - research, search and favs

**Comment by esgoodman** [comment]
@wongperson do you want to rewrite this epic to include page wireframing too?

**Comment by RyanSibley** [comment]
Outline here: https://docs.google.com/document/d/11MplpLGNLRL4ygFlcPAzFsJzWngP9j8mwekK7eZZ2n4/edit?usp=sharing

I spoke with Robin and Chris and the next steps are to talk with their comms unit to establish what content goes here and what goes on the broader State dept website.

**Comment by cydneycappello** [comment]
From yesterday's meeting:
- The About page will link back to an internal Department of State website
- Robin will provide the team a link

**Comment by burgwyn** [comment]
@Icemanbeta - can you set up an environment variable and inject it into the About link?

**Comment by RyanSibley** [comment]
To clarify, we are still debating what content will populate an About page. It is clear, however, that the partner wants to link to an internal resources page on their website for some content. But what content that is exactly is still being discussed internally by the partner. 

In the meantime, you can go to the link above, or request a word version from me or Cydney, to see the outline I reviewed with the partner.

**Comment by RyanSibley** [comment]
From Robin: 

> The About page on TalentMAP (at this time) will have a paragraph, an overview of TalentMAP and a link which will take the bidders to the main HR portal of HR System Online Resources where an overview of TalentMAP, training and guidance tools reside.

cc @burgwyn @cydneycappello

**Comment by cydneycappello** [comment]
@mjoyce91 Here is the About Page:
![a about page](https://user-images.githubusercontent.com/13770123/38955425-a85b2b18-4322-11e8-8dbe-f832f8602079.jpg)
Notes:
- The 'Email TalentMAP' button goes to TalentMAP@state.gov
- We are still waiting on the HR Systems Online Resources link from Robin.
