### ISSUE TITLE
Update 'How to Bid' To Match Styleguide Tone

### ISSUE THREAD

**Issue by cydneycappello** [USStateDept/State-TalentMAP#1754]
On the position page, the 'How to Bid' content should match the tone of the content styleguide.

### Current
Current language follows the Knowledeable and Professional tone we want to represent. 

**How to bid**
You can't yet bid for a position using TalentMAP. If you've decided you want to bid for this position, you still need to sign in to the FSBid system.

<img width="464" alt="screen shot 2018-04-12 at 12 23 02 pm" src="https://user-images.githubusercontent.com/13770123/38690590-76151914-3e4c-11e8-9388-eaa8e696d4ba.png">

### Desired
Could we update the language to also include our Enthusiastic and Welcoming tone attributes?

**Comment by RyanSibley** [comment]
@cydneycappello and @esgoodman I tried focusing on what a user *can do* for this copy: 

`If you've found a position you want to apply for, please continue to <link>FSBid to apply</link>! Add jobs interested in to your TalentMAP favorites list by clicking the star.` 

What do y'all think?

**Comment by esgoodman** [comment]
Could shorten and combine the two? The headline for the section is `How to bid,` so I'm not sure we need to restate it in the body copy. Maybe something like...

`TalentMAP is under development. Please <https://hrweb.hr.state.sbu/hronline/main.cfm/32>go to FSBid</a> to bid on this position. You can find it there using the position number.`

**Comment by cydneycappello** [comment]
@esgoodman I think this is a good start to shortening it, however, I think it's very important that Robin's version establishes TalentMAP as a research tool. We want bidders to know that even though they can not submit a bid from TalentMAP, they can at least find everything they need to know.

**Comment by esgoodman** [comment]
In retrospect -- I actually don't think I should be rewriting at all! Let's go with Robin's copy and see how it goes.
