### ISSUE TITLE
Create Danger Pay and Post Differential Disclaimers

### ISSUE THREAD

**Issue by cydneycappello** [USStateDept/State-TalentMAP#1755]
We may need to add a disclaimer anywhere we see Danger Pay and Post Differential percentages to inform users that the data they see may not be up to date, but that they can visit the Overseas Briefing Center for the latest information.

### Currently
We do not have any information about the data being provided for Danger Pay and Post Differential.

### Desired
It'd be nice to include a tooltip on all of the headers that include Danger Pay and Post Differential with language such as:

1.  "The Danger Pay data you see here is representative and may not be the most up to date. For the latest information regarding Danger Pay, visit the [Overseas Briefing Center](https://aoprals.state.gov/Web920/danger_pay_all.asp) website."
2. "The Post Differential data you see here is representative and may not be the most up to date. For the latest information regarding Post Differential, visit the [Overseas Briefing Center](https://aoprals.state.gov/Web920/hardship.asp) website."

@RyanSibley Do you have any suggestions for the above language?

**Comment by RyanSibley** [comment]
1.  "The Danger Pay data you see here might not be up to date. For the latest information regarding Danger Pay, visit the [Overseas Briefing Center](https://aoprals.state.gov/Web920/danger_pay_all.asp) website."
2. "The Post Differential data you see here might not be up to date. For the latest information regarding Post Differential, visit the [Overseas Briefing Center](https://aoprals.state.gov/Web920/hardship.asp) website."
