### ISSUE TITLE
Paper prototype Bidding Cycles

### ISSUE THREAD

**Issue by burgwyn** [USStateDept/State-TalentMAP#188]
Paper prototype the simplest version of cycle-filtering/switching for positions. (Ability to select one cycle at a time instead of multiple cycles.) Go into State with human users to test whether or not simplest approach works.

Test or provide options for representations of bidding cycles and filters

Outcomes
* Grooming for #189 
* Design sketches

**Comment by krisdelacruz** [comment]
Will need to gather information on how to facilitate Design Studio session for Bidding Cycles. 18F will find a resource to help faciliate the session.

**Comment by wongperson** [comment]
@cydneycappello @afrasier Clarify the process and the source of record for how cycles are populated with Bureau and RMA input.

**Comment by cydneycappello** [comment]
Here are the paper prototypes of how we could include Bid Cycle and Projected Vacancy in TalentMAP. Before each prototype, I've broken down key features.

**Homepage:**
-  Added a section to the homepage called, "Positions in Bid Cycle" which would show the user a sampling of positions in their grade, in the current bid cycle(s)
- The title will be hyperlinked to a pre-filtered search showing results for Open Bid Cycles in Grade
- Added a symbol (fire) to show position in current bid cycles to give users a sense of urgency and make these positions stand out among all positions, which will be carried through on the homepage-style cards as well as the search results cards

![paper-prototype-homepage](https://user-images.githubusercontent.com/13770123/38258847-89a79f14-3731-11e8-994b-2e7659be2de7.png)

**Search Results View**
- Carried over fire symbol to differentiate position in bid cycle. These positions will also show the "Transfer eligibility date: MM/DD/YYYY" of the position.
- Added a date picker to the top of the results where users can choose a range of time for research, which is targeted at bidders researching projected vacancies.
- If a position is a projected vacancy, then the area of the card where "Transfer eligibility date" would appear, is replaced by "Projected vacancy: MM/DD/YYYY."
- There is a Bid Cycle filter where users could select a Bid Cycle and only that Bid Cycle's position would appear in results.

![paper-prototype-filters](https://user-images.githubusercontent.com/13770123/38258825-79baf286-3731-11e8-957e-00103e892013.png)

**Comment by cydneycappello** [comment]
Updated paper prototype into a clickable prototype with two directions of "time" selection for testing:
- [Direction 1](https://bahdigital.invisionapp.com/share/ZYGQ9LB6598) 
- [Direction 2](https://bahdigital.invisionapp.com/share/Z4GQ9L2AHY7)

Testing will take place Monday, April 9.

**Comment by cydneycappello** [comment]
While testing did not pan out, we included Bid Cycles as a filter in search.
