### ISSUE TITLE
Compare View - No Link Back

### ISSUE THREAD

**Issue by burgwyn** [USStateDept/State-TalentMAP#444]
The Compare Positions view lacks the ability to navigate back to search results list:
<img width="1136" alt="screen shot 2017-08-25 at 2 26 37 pm" src="https://user-images.githubusercontent.com/661204/29779832-bf9179fc-8be1-11e7-9c7a-ce680b0603ff.png">

**Comment by cydneycappello** [comment]
There is now a back to search results button.
