### ISSUE TITLE
"Here's how you know" text and up-down caret are too close

### ISSUE THREAD

**Issue by jseppi** [USStateDept/State-TalentMAP#458]
Currently the text and caret are too close together:

<img width="125" alt="screen shot 2017-09-05 at 2 30 40 pm" src="https://user-images.githubusercontent.com/697848/30079744-ded2227e-9246-11e7-8346-681d1990cd2f.png">

You could either add a space right before the closing `</span>` on this line: https://github.com/18F/State-TalentMAP/blob/dev/src/Components/Header/GovBanner/GovBanner.jsx#L18
or adjust some CSS on the `:after` that adds the caret. I didn't notice any obvious differences between the markup here and that in the USWDS, so I'm not quite sure why it doesn't look as it does  at the top of https://standards.usa.gov/

**Comment by mjoyce91** [comment]
Huh, that is odd! Good eye.
