### ISSUE TITLE
Search Results Card Content Updates

### ISSUE THREAD

**Issue by krisdelacruz** [USStateDept/State-TalentMAP#656]
**Story**

As a designer of TalentMap,
I need to present and get approval on the search results card content
So that it is consistent with the designs

**Background:** 
GSA provided insight and feedback on the "Search Results" card and would like to get a condensed view of the content. The first version of the cards was the first pass and would like to iterate. 

**Questions to answer**
Will the users want to see more position based content?
Will the user want to see position and post based content?

**Testing**
Let's conduct a second round of first click analysis, A/B Testing or usability testing for this task. Will discuss on whats the best approach would be. 

**Goals**
We would like to get user's feedback on what information they would like to see on the search results cards.

**Steps**
- [ ]  @krisdelacruz puts together screenshots of current wireframes
- [ ]  @krisdelacruz Presents both version of the search results cards to the Product Owner
- [ ]  Get feedback from product team 
- [ ]  Prepare for testing
- [ ]  Development team makes updates from client feedback
- [ ]  Prepare for testing

**Acceptance criteria**
Gather 3-5 Users
Draft usability test plan
Conduct remote usability testing on Adobe Connect
Present finding to Product team

**Comment by cydneycappello** [comment]
Moving issue to done because we tested this with users in March.
