### ISSUE TITLE
Cloned Saved Search Duplicate/Available Name Check

### ISSUE THREAD

**Issue by mjoyce91** [USStateDept/State-TalentMAP#668]
As a developer,
I want an API endpoint that checks whether the name for a Saved Search is taken,
So that users can clone saved searches with logical and unique names.

Similarly, it may be that the API should handle the naming of the cloned search on its own, so that it can apply logic to decide what to name the cloned search.

**Comment by afrasier** [comment]
Would it be better to just add `/api/v1/searches/{id}/clone/` to do the cloning and handle the automatic naming logic, and return the cloned item?

**Comment by burgwyn** [comment]
That would turn 2 API calls into 1, correct?

**Comment by afrasier** [comment]
Yes, instead of checking name and then posting, we just add a clone action

**Comment by mjoyce91** [comment]
That works for me.
