### ISSUE TITLE
Define Bid List Alerts

### ISSUE THREAD

**Issue by krisdelacruz** [USStateDept/State-TalentMAP#780]
### Story
As a designer of TalentMap, 
I need to edit the language for the bid list alerts
So that it caters to DoS language and timelines

<img width="1099" alt="screen shot 2017-10-18 at 11 36 19 am" src="https://user-images.githubusercontent.com/16211502/31727959-05514ea6-b3f9-11e7-869e-150d1e4c4e4b.png">

<img width="794" alt="screen shot 2017-10-18 at 11 40 48 am" src="https://user-images.githubusercontent.com/16211502/31728030-3618463e-b3f9-11e7-9194-d95961c758f5.png">

<img width="793" alt="screen shot 2017-10-18 at 11 40 45 am" src="https://user-images.githubusercontent.com/16211502/31728044-3ce47abe-b3f9-11e7-9e71-72390b2c0526.png">

### Acceptance Criteria
• Explore different iconography

**Comment by wongperson** [comment]
@krisdelacruz I think this is complete, are we okay to close this?
