### ISSUE TITLE
Tour of Duty on Position

### ISSUE THREAD

**Issue by burgwyn** [USStateDept/State-TalentMAP#787]
As a bidder,
I need to view the specific tour of duty information for a position
So that I have accurate tour of duty information

## Acceptance criteria
* Tour of duty is added to position model

**Comment by jseppi** [comment]
So do Posts also have "default" tours-of-duty, or should they only be specified on each Position?

**Comment by afrasier** [comment]
Posts have a standard TOD, but each Position can vary. I think generally, most positions at a post are the standard TOD, but there are outliers.

**Comment by cydneycappello** [comment]
Tour of duty has been included in the search results cards AND the position detail page.
