### ISSUE TITLE
UI - Implement Compare List

### ISSUE THREAD

**Issue by mjoyce91** [USStateDept/State-TalentMAP#850]
As a user,
I want to see a running list of my comparisons at the bottom of the screen,
So that I'm always aware of my current comparison selections while browsing position search results.

## Acceptance criteria
- Visual design of the compare list wireframes is applied to the front-end web application

**Comment by krisdelacruz** [comment]
![03_00_position comparison option a](https://user-images.githubusercontent.com/16211502/33999597-df03d894-e0b8-11e7-993d-1183abf35f69.jpg)


![02_00_search results page](https://user-images.githubusercontent.com/16211502/33999500-a51f4fa0-e0b8-11e7-8a3f-030c0fc62852.jpg)
